/*
Copyright Obaydullah.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	pritamdasdevv1alpha1 "github.com/PritamDas17021999/sample-controller/pkg/apis/pritamdas.dev/v1alpha1"
	versioned "github.com/PritamDas17021999/sample-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/PritamDas17021999/sample-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/PritamDas17021999/sample-controller/pkg/client/listers/pritamdas.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PritamInformer provides access to a shared informer and lister for
// Pritams.
type PritamInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PritamLister
}

type pritamInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPritamInformer constructs a new informer for Pritam type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPritamInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPritamInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPritamInformer constructs a new informer for Pritam type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPritamInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PritamdasV1alpha1().Pritams(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PritamdasV1alpha1().Pritams(namespace).Watch(context.TODO(), options)
			},
		},
		&pritamdasdevv1alpha1.Pritam{},
		resyncPeriod,
		indexers,
	)
}

func (f *pritamInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPritamInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pritamInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&pritamdasdevv1alpha1.Pritam{}, f.defaultInformer)
}

func (f *pritamInformer) Lister() v1alpha1.PritamLister {
	return v1alpha1.NewPritamLister(f.Informer().GetIndexer())
}
