/*
Copyright Obaydullah.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/PritamDas17021999/sample-controller/pkg/apis/pritamdas.dev/v1alpha1"
	pritamdasdevv1alpha1 "github.com/PritamDas17021999/sample-controller/pkg/client/applyconfiguration/pritamdas.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePritams implements PritamInterface
type FakePritams struct {
	Fake *FakePritamdasV1alpha1
	ns   string
}

var pritamsResource = v1alpha1.SchemeGroupVersion.WithResource("pritams")

var pritamsKind = v1alpha1.SchemeGroupVersion.WithKind("Pritam")

// Get takes name of the pritam, and returns the corresponding pritam object, and an error if there is any.
func (c *FakePritams) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Pritam, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pritamsResource, c.ns, name), &v1alpha1.Pritam{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pritam), err
}

// List takes label and field selectors, and returns the list of Pritams that match those selectors.
func (c *FakePritams) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PritamList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pritamsResource, pritamsKind, c.ns, opts), &v1alpha1.PritamList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PritamList{ListMeta: obj.(*v1alpha1.PritamList).ListMeta}
	for _, item := range obj.(*v1alpha1.PritamList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pritams.
func (c *FakePritams) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pritamsResource, c.ns, opts))

}

// Create takes the representation of a pritam and creates it.  Returns the server's representation of the pritam, and an error, if there is any.
func (c *FakePritams) Create(ctx context.Context, pritam *v1alpha1.Pritam, opts v1.CreateOptions) (result *v1alpha1.Pritam, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pritamsResource, c.ns, pritam), &v1alpha1.Pritam{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pritam), err
}

// Update takes the representation of a pritam and updates it. Returns the server's representation of the pritam, and an error, if there is any.
func (c *FakePritams) Update(ctx context.Context, pritam *v1alpha1.Pritam, opts v1.UpdateOptions) (result *v1alpha1.Pritam, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pritamsResource, c.ns, pritam), &v1alpha1.Pritam{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pritam), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePritams) UpdateStatus(ctx context.Context, pritam *v1alpha1.Pritam, opts v1.UpdateOptions) (*v1alpha1.Pritam, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pritamsResource, "status", c.ns, pritam), &v1alpha1.Pritam{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pritam), err
}

// Delete takes name of the pritam and deletes it. Returns an error if one occurs.
func (c *FakePritams) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(pritamsResource, c.ns, name, opts), &v1alpha1.Pritam{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePritams) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pritamsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PritamList{})
	return err
}

// Patch applies the patch and returns the patched pritam.
func (c *FakePritams) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Pritam, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pritamsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Pritam{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pritam), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied pritam.
func (c *FakePritams) Apply(ctx context.Context, pritam *pritamdasdevv1alpha1.PritamApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Pritam, err error) {
	if pritam == nil {
		return nil, fmt.Errorf("pritam provided to Apply must not be nil")
	}
	data, err := json.Marshal(pritam)
	if err != nil {
		return nil, err
	}
	name := pritam.Name
	if name == nil {
		return nil, fmt.Errorf("pritam.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pritamsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.Pritam{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pritam), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakePritams) ApplyStatus(ctx context.Context, pritam *pritamdasdevv1alpha1.PritamApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Pritam, err error) {
	if pritam == nil {
		return nil, fmt.Errorf("pritam provided to Apply must not be nil")
	}
	data, err := json.Marshal(pritam)
	if err != nil {
		return nil, err
	}
	name := pritam.Name
	if name == nil {
		return nil, fmt.Errorf("pritam.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pritamsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.Pritam{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pritam), err
}
